"""YAML emitter for the merged chip dict.

Uses a custom representer to render hex literals for addresses and sizes
(`0x40000000` is more readable than `1073741824` for chip data), and to
preserve key order from the merge step (rather than alphabetizing).
"""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path
from typing import Any

import yaml


class _HexInt(int):
    """Wrapper class so we can emit specific ints in hex without coloring all ints."""


def _represent_hex_int(dumper: yaml.SafeDumper, data: _HexInt) -> yaml.ScalarNode:
    return dumper.represent_scalar("tag:yaml.org,2002:int", f"0x{int(data):X}")


def _represent_dict_preserve_order(dumper: yaml.SafeDumper, data: dict) -> yaml.MappingNode:
    return dumper.represent_dict(data.items())


class _ChipDumper(yaml.SafeDumper):
    pass


_ChipDumper.add_representer(_HexInt, _represent_hex_int)
_ChipDumper.add_representer(dict, _represent_dict_preserve_order)
_ChipDumper.add_representer(OrderedDict, _represent_dict_preserve_order)


_HEX_KEYS = {
    "base", "vector_offset", "mask",
    "offset", "reset",
    "usb_vid", "usb_pid",
    "flash_start_address",
}


def _convert_hex(obj: Any) -> Any:
    """Recursively wrap integers in _HexInt when their dict key marks them as addresses."""
    if isinstance(obj, dict):
        return {k: _convert_hex_value(k, v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_convert_hex(v) for v in obj]
    return obj


def _convert_hex_value(key: str, value: Any) -> Any:
    if isinstance(value, dict):
        return _convert_hex(value)
    if isinstance(value, list):
        return [_convert_hex(v) for v in value]
    if isinstance(value, int) and not isinstance(value, bool) and key in _HEX_KEYS:
        return _HexInt(value)
    return value


def emit_chip_yaml(chip_data: dict[str, Any], target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    cleaned = _convert_hex(chip_data)
    with target.open("w", encoding="utf-8") as fh:
        fh.write("# Generated by wb32-data — do not edit by hand.\n")
        fh.write("# Source: data-gen/recipes/parts.yaml entry plus vendor headers,\n")
        fh.write("# ChibiOS-Contrib WB32 port, and Westberry datasheet PDFs.\n")
        yaml.dump(
            cleaned,
            fh,
            Dumper=_ChipDumper,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=True,
            width=120,
        )


def emit_yaml(data: dict[str, Any], target: Path, *, header: str = "") -> None:
    """General-purpose YAML emitter used for shared peripheral and interrupt files."""
    target.parent.mkdir(parents=True, exist_ok=True)
    cleaned = _convert_hex(data)
    with target.open("w", encoding="utf-8") as fh:
        if header:
            for line in header.splitlines():
                fh.write(f"# {line}\n" if not line.startswith("#") else f"{line}\n")
        yaml.dump(
            cleaned,
            fh,
            Dumper=_ChipDumper,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=True,
            width=120,
        )
